# Generated by Django 5.2.7 on 2026-08-11 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('demo_numbers_4', models.CharField(blank=True, max_length=4)),
                ('demo_numbers_6', models.CharField(blank=True, max_length=6)),
                ('amount', models.CharField(blank=True, max_length=20)),
                ('term', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending_4', 'Waiting 4-number approval'), ('approved_4', '4 numbers approved'), ('rejected_4', '4 numbers rejected'), ('pending_6', 'Waiting 6-number approval'), ('approved_6', '6 numbers approved'), ('rejected_6', '6 numbers rejected'), ('completed', 'Completed')], default='pending_4', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
